site_name: Weave Ignite
# site_description:
site_author: Weave Ignite Project
site_url: https://ignite.readthedocs.io

# Repository
repo_name: weaveworks/ignite
repo_url: https://github.com/weaveworks/ignite
edit_uri: ""

theme:
  name: material
  logo: logo.png
  language: en
  feature:
    tabs: false
  palette:
    primary: blue
    accent: indigo
  highlightjs: true

docs_dir: docs

extra_css:
  - _static/custom.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.tabbed
  - toc:
      permalink: true
