name: Release OS images

on:
  workflow_dispatch:
    # Enable manual trigger of this action.
    inputs:
      user:
        description: Container registry user.
        default: weaveworks
        required: true
      version:
        description: ignite version used for image tags.
        required: true

env:
  DOCKER_USER: ${{ github.event.inputs.user }}
  VERSION: ${{ github.event.inputs.version }}

defaults:
  run:
    working-directory: images

jobs:
  image-build-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        what: [alpine, amazon-kernel, amazonlinux, centos, kubeadm, opensuse, ubuntu, k3s, almalinux, rockylinux]
    steps:
      - uses: actions/checkout@v2
      - name: Login to container registry
        uses: docker/login-action@v1.12.0
        with:
          registry: docker.io
          username: weaveworksigniteci
          password: ${{ secrets.DOCKERHUB_PASSWORD_WEAVEWORKSIGNITECI }}
      - run: make OP=build build-${{ matrix.what }}
      - run: make OP=push build-${{ matrix.what }}
